### ISSUE TITLE
Facing error java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by SonaliSihra** [dmarcas/locustapitest#5]
I'm facing error java.lang.ArrayIndexOutOfBoundsException: -1 at for (int i= 2; i<datasetData.get((datasetData.size()-1)).length; i++) i'm not able to understand why i'm getting this error.

```
PFB code block:

    private CategoryDataset createDataset(String path){
    	DefaultCategoryDataset dataset = new DefaultCategoryDataset();
    	List<String[]> datasetData = FileOperations.getInstance().readCSV(path);
    	for (int i= 2; i<datasetData.get((datasetData.size()-1)).length; i++) {
    		dataset.setValue(Integer.parseInt(datasetData.get((datasetData.size()-1))[i]), "Requests", datasetData.get(0)[i]);    		
    	}
    	return dataset;
    }
```
I have cloned the project set the user, timezone and os after that tried to do mvn clean install in my ubuntu 18.04, It is asking for a csv file. Are we supposed to make it manually? or there is something I'm doing wrong in it. 
I debuted and found that it is searching for the file and giving : java.io.FileNotFoundException: /home/sonali/locustapitest/target/csvlocustsresults/performanceResults_distribution.csv (No such file or directory)

**Comment by dmarcas** [comment]
Hi @SonaliSihra , most probably doesn't find the correct csv file due that you have a higher version of locust, ensure that you have installed locust 0.13.5 (the csv file is created by locust automatically and depending on the locust version the csv file change). In any case, this repository was discontinued in favour of the following development https://github.com/NightCodeLabs/pretzel-example, in which we are working on.

Please, use the repositori mentioned and let me know if you have any problem.

**Comment by SonaliSihra** [comment]
Hi @dmarcas , while trying to build the pretzel-example in IntelliJ I'm facing error :Error:java: invalid source release: 9, I'm using java version 8.

**Comment by SonaliSihra** [comment]
[response.txt](https://github.com/dmarcas/locustapitest/files/4879833/response.txt)
@dmarcas  Also, i tried the locustapitest with the locust version you mentioned, it did give some response but the same error:
```
Jul 06, 2020 8:39:37 PM helpers.FileOperations readCSV
SEVERE: Something went wrong reading the CSV Report file
Jul 06, 2020 8:39:37 PM performance.LocustOperations checkMaxResponseTime
SEVERE: Something went wrong cheking the MaxResponseTime
Jul 06, 2020 8:39:37 PM helpers.FileOperations readCSV
SEVERE: Something went wrong reading the CSV Report file
{
    "answer": "yes",
    "forced": true,
    "image": "https://yesno.wtf/assets/yes/9-6403270cf95723ae4664274db51f1fd4.gif"
}
{
    "answer": "yes",
    "forced": true,
    "image": "https://yesno.wtf/assets/yes/9-6403270cf95723ae4664274db51f1fd4.gif"
}

```

**Comment by dmarcas** [comment]
> Hi @dmarcas , while trying to build the pretzel-example in IntelliJ I'm facing error :Error:java: invalid source release: 9, I'm using java version 8.

@SonaliSihra , you should be able to use java 9 for the project (install it if you don't have it yet and select jdk 9 for this project in intellij from project structure).

**Comment by dmarcas** [comment]
> @dmarcas Also, i tried the locustapitest with the locust version you mentioned, it did give some response but the same error:
> 
> ```
> Jul 06, 2020 8:39:37 PM helpers.FileOperations readCSV
> SEVERE: Something went wrong reading the CSV Report file
> Jul 06, 2020 8:39:37 PM performance.LocustOperations checkMaxResponseTime
> SEVERE: Something went wrong cheking the MaxResponseTime
> Jul 06, 2020 8:39:37 PM helpers.FileOperations readCSV
> SEVERE: Something went wrong reading the CSV Report file
> {
>     "answer": "yes",
>     "forced": true,
>     "image": "https://yesno.wtf/assets/yes/9-6403270cf95723ae4664274db51f1fd4.gif"
> }
> {
>     "answer": "yes",
>     "forced": true,
>     "image": "https://yesno.wtf/assets/yes/9-6403270cf95723ae4664274db51f1fd4.gif"
> }
> ```

@SonaliSihra sorry, 0.13.5 is for  https://github.com/NightCodeLabs/pretzel-example, maybe try to downgrade to 0.11.0. As I said, the repository was changed and there are things moved and improved in pretzel.

**Comment by SonaliSihra** [comment]
> > @dmarcas Also, i tried the locustapitest with the locust version you mentioned, it did give some response but the same error:
> > ```
> > Jul 06, 2020 8:39:37 PM helpers.FileOperations readCSV
> > SEVERE: Something went wrong reading the CSV Report file
> > Jul 06, 2020 8:39:37 PM performance.LocustOperations checkMaxResponseTime
> > SEVERE: Something went wrong cheking the MaxResponseTime
> > Jul 06, 2020 8:39:37 PM helpers.FileOperations readCSV
> > SEVERE: Something went wrong reading the CSV Report file
> > {
> >     "answer": "yes",
> >     "forced": true,
> >     "image": "https://yesno.wtf/assets/yes/9-6403270cf95723ae4664274db51f1fd4.gif"
> > }
> > {
> >     "answer": "yes",
> >     "forced": true,
> >     "image": "https://yesno.wtf/assets/yes/9-6403270cf95723ae4664274db51f1fd4.gif"
> > }
> > ```
> 
> @SonaliSihra sorry, 0.13.5 is for https://github.com/NightCodeLabs/pretzel-example, maybe try to downgrade to 0.11.0. As I said, the repository was changed and there are things moved and improved in pretzel.

**I was able to solve the following issues by doing some changes:**
**Issue 1:** The folder target/csvlocustsresults was not getting created automatically once mvn clean install is done so I fixed that by adding maven-antrun-plugin in pom.xml. Also as I have locust 0.13.5 running on python version 3.5 and in that the distributed and requests CSV are getting created with another name hence changed both in src/main/resources/configs/config.properties
```
requestsReportLocation=target/csvlocustsresults/performanceResults_stats.csv
distributionReportLocation=target/csvlocustsresults/performanceResults_stats_history.csv
```
**Issue 2:** I was facing NumberFormatException : fixed that by changing the parsing from Integer to Float in method createDataset()  and checkMaxResponseTime() 

**Issue 3:** No wait time was mentioned in the dummy python file. Added wait_time = between(5, 9) under class Dummy(Locust)

As you mentioned that this project is discontinued in favour of the following development still this project is serving the exact purpose I wanted to try. Hope this would help.
Thanks, @dmarcas appreciate your help!

**Comment by dmarcas** [comment]
@SonaliSihra thanks. 

It's very important to allign the locust version with the locustBarChart.class due that depending on the version the csv file generated could change, and then you will need to do some changes.

**Issue 1:** yes. This is one of the things that changes depending on the version of locust installed (the name of the report and its content).

**Issue 2**, should be an Integer, due that here we are recovering the load distribution and they are integer values (if you have a different version of locust, take a look in which values you are gathering from the csv file, because the content could change and most probably you are gathering another values and this could be the reason that you need to parse to float).

**Issue 3**, related to wait time: In this case, we are launching Locust master in a distributed mode and locust wait to start the test once the client is connected and stops once the test time is finished, by himself (no wait time is needed). Anyway, this is managed in pretzel (https://github.com/NightCodeLabs/pretzel-example) waiting for the system task stopped, to launch the next run.

I really encourage you to use pretzel and contribute to his improvement (it will be really good your contribution).

Regards,
